spring.application.name=oktoberfest
# Database connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect (optional in newer Spring Boot versions)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

manager.password.hash=${MANAGER_PASSWORD_HASH}
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=3600000