spring.application.name=oktoberfest
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/oktoberfest
spring.datasource.username=koda
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect (optional in newer Spring Boot versions)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

manager.password.hash=$2a$12$bvMVPFWrVIjhkUPkeYfrqe9q11iru.jXsKSpv5Ep/hGmk2wfE65pm
jwt.secret=niggaerfhdposchdfjgtqvcgdhfnmsds
jwt.expiration-ms=3600000